//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_SUB_CATEGORIA
    {
        public int ID_SUB_CATEGORIA { get; set; }
        public int ID_CATEGORIA { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int ID_USUARIO_CREACION { get; set; }
        public string FECHA_ACTUALIZACION { get; set; }
        public int ID_USUARIO_ACTUALIZACION { get; set; }
    
        public virtual CAT_CATEGORIA CAT_CATEGORIA { get; set; }
        public virtual TBL_RELACIION TBL_RELACIION { get; set; }
    }
}
