//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CALIFICACION_NEGOCIO
    {
        public int ID_CALIFICACION { get; set; }
        public Nullable<int> ID_NEGOCIO { get; set; }
        public Nullable<double> CALIFICACION { get; set; }
        public string COMETARIOS { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual CAT_NEGOCIO CAT_NEGOCIO { get; set; }
    }
}
