//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_USUARIO_NEGOCIO
    {
        public int ID_USUARIO_NEGOCIO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> ID_NEGOCIO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<int> ID_USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
        public Nullable<int> ID_USUARIO_ACTUALIZACION { get; set; }
    
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        public virtual CAT_NEGOCIO CAT_NEGOCIO { get; set; }
    }
}
